### ISSUE TITLE
contextual-code-completion.pdf : Shawn

### ISSUE THREAD

**Issue by RoyLQ** [RoyLQ/Advanced_IDE_Recommendation#2]
READ contextual-code-completion.pdf

**Comment by SNett00** [comment]
[Paper Summary - Machine Learning.docx](https://github.com/RoyLQ/Advanced_IDE_Recommendation/files/7272482/Paper.Summary.-.Machine.Learning.docx)


Adding the summary document. Can change the format if needed.

**Comment by SNett00** [comment]
[Paper Summary - Machine Learning.pdf](https://github.com/RoyLQ/Advanced_IDE_Recommendation/files/7272485/Paper.Summary.-.Machine.Learning.pdf)

Also added PDF version
